services:
  devcontainer:
    image: mcr.microsoft.com/devcontainers/go:0-1.20
    # Overrides default command so things don't shut down after the process ends.
    command: /bin/sh -c "while sleep 1000; do :; done"
    # Required for ptrace-based debuggers like C++, Go, and Rust
    cap_add:
    - SYS_PTRACE
    security_opt:
    - seccomp:unconfined
    # Runs the service on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    network_mode: service:mongo
